version: 0.1
phases:
  install:
    commands:
        - aws --version
        - easy_install pip
        - pip install --upgrade awscli
        - aws --version
  build:
    commands:
        - aws ec2 describe-instances
  post_build:
    commands:
artifacts:
  files:
